name: Deploy to Neocities

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Neocities
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: neocities.org
          username: digisw
          password: ${{ secrets.NEOCITIES_API_KEY }}